controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController
    twist_controller:
      type: picknik_twist_controller/PicknikTwistController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    velocity_force_controller:
      type: velocity_force_controller/VelocityForceController

joint_trajectory_controller:
  ros__parameters:
    gains:
      j2n6s300_joint_1:
        angle_wraparound: true
      j2n6s300_joint_4:
        angle_wraparound: true
      j2n6s300_joint_5:
        angle_wraparound: true
      j2n6s300_joint_6:
        angle_wraparound: true
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    state_publish_rate: 200.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      j2n6s300_joint_1:
        goal: 0.05
      j2n6s300_joint_2:
        goal: 0.05
      j2n6s300_joint_3:
        goal: 0.05
      j2n6s300_joint_4:
        goal: 0.05
      j2n6s300_joint_5:
        goal: 0.05
      j2n6s300_joint_6:
        goal: 0.05

joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    base_frame: root
    sensor_frame: j2n6s300_end_effector
    ee_frame: j2n6s300_end_effector
    ft_sensor_name: fts
    stop_accelerations: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0]

twist_controller:
  ros__parameters:
    joint: tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: j2n6s300_joint_finger_1
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02


servo_controller:
  ros__parameters:
    gains:
      j2n6s300_joint_1:
        angle_wraparound: true
      j2n6s300_joint_4:
        angle_wraparound: true
      j2n6s300_joint_5:
        angle_wraparound: true
      j2n6s300_joint_6:
        angle_wraparound: true
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      j2n6s300_joint_1:
        goal: 0.05
      j2n6s300_joint_2:
        goal: 0.05
      j2n6s300_joint_3:
        goal: 0.05
      j2n6s300_joint_4:
        goal: 0.05
      j2n6s300_joint_5:
        goal: 0.05
      j2n6s300_joint_6:
        goal: 0.05

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: fts
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: j2n6s300_end_effector

velocity_force_controller:
  ros__parameters:
    planning_group_name: manipulator
    sensor_frame: j2n6s300_end_effector
    ee_frame: j2n6s300_end_effector
    ft_sensor_name: fts
    ft_force_deadband: 2.0
    ft_torque_deadband: 1.0
    max_joint_velocity:
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 0.524
    max_joint_acceleration:
      - 52.4
      - 52.4
      - 52.4
      - 52.4
      - 52.4
      - 52.4
    max_cartesian_velocity:
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
      - 0.25
    max_cartesian_acceleration:
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
