###############################################
# Modify all parameters related to servoing here
###############################################

move_group_name: manipulator
planning_frame: root
ee_frame_name: j2n6s300_end_effector # or end_effector
command_in_type: "unitless"
scale:
  linear: 0.5
  rotational: 1.0
command_out_type: trajectory_msgs/JointTrajectory
publish_joint_positions: true
