# Default initial positions for j2n6s300's ros2_control fake system

initial_positions:
  j2n6s300_joint_1: 3.1415
  j2n6s300_joint_2: 3.1415
  j2n6s300_joint_3: 3.1415
  j2n6s300_joint_4: 3.1415
  j2n6s300_joint_5: 3.1415
  j2n6s300_joint_6: 3.1415
  j2n6s300_joint_finger_1: 0
  j2n6s300_joint_finger_2: 0
  j2n6s300_joint_finger_3: 0
  j2n6s300_joint_finger_tip_1: 0
  j2n6s300_joint_finger_tip_2: 0
  j2n6s300_joint_finger_tip_3: 0