controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    # The gripper controller just relays position commands
    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    gains:
      j2n6s300_joint_1:
        angle_wraparound: true
      j2n6s300_joint_4:
        angle_wraparound: true
      j2n6s300_joint_5:
        angle_wraparound: true
      j2n6s300_joint_6:
        angle_wraparound: true
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      j2n6s300_joint_1:
        goal: 0.05
      j2n6s300_joint_2:
        goal: 0.05
      j2n6s300_joint_3:
        goal: 0.05
      j2n6s300_joint_4:
        goal: 0.05
      j2n6s300_joint_5:
        goal: 0.05
      j2n6s300_joint_6:
        goal: 0.05

twist_controller:
  ros__parameters:
    joint: tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

hand_controller:
  ros__parameters:
    default: true
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_3
      - j2n6s300_joint_finger_tip_1
      - j2n6s300_joint_finger_tip_2
      - j2n6s300_joint_finger_tip_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

servo_controller:
  ros__parameters:
    gains:
      j2n6s300_joint_1:
        angle_wraparound: true
      j2n6s300_joint_4:
        angle_wraparound: true
      j2n6s300_joint_5:
        angle_wraparound: true
      j2n6s300_joint_6:
        angle_wraparound: true
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      j2n6s300_joint_1:
        goal: 0.05
      j2n6s300_joint_2:
        goal: 0.05
      j2n6s300_joint_3:
        goal: 0.05
      j2n6s300_joint_4:
        goal: 0.05
      j2n6s300_joint_5:
        goal: 0.05
      j2n6s300_joint_6:
        goal: 0.05